//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTy.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class BaoCao
    {
        public string Id { get; set; }
        public string TieuDe { get; set; }

        [AllowHtml]
        public string NoiDung { get; set; }
        public string MaNV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
